name: uaepass_flutter
description: Unofficial reusable Flutter integration for UAE PASS authentication, designed for future digital-signing support.
version: 0.0.1
homepage: https://github.com/abqamar/uaepass_flutter
repository: https://github.com/abqamar/uaepass_flutter
license: MIT

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  app_links: ^6.4.1
  flutter_inappwebview: ^6.2.0-beta.3
  flutter_device_apps: ^0.8.1
  http: ^1.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
